### ISSUE TITLE
library version required.

### ISSUE THREAD

**Issue by recordmp3** [chenkaisun/MMLI1#1]
I appreciate your good work! 
Could you please provide with more info of versions of your library? 

For example, versions of library in requirement.txt (you can see that many of them are not clear)

![image](https://user-images.githubusercontent.com/33998409/202368870-955ae6b6-29f9-4c30-a19b-a9038615bbee.png)

And also the version of pyg and pytorch RDKit.
![image](https://user-images.githubusercontent.com/33998409/202368992-7b729374-3903-4701-817d-729a9dcebff1.png)

thank you in advance!

**Comment by chenkaisun** [comment]
Thanks for your interest. The unversioned libraries are nonessential for running PyTorch code (they are mostly for collecting data). RDKit I used the 2021/5 version, PyTorch is 1.6, and Geometric is 1.7. Let me know if you meet a problem. Thanks.
